name: "Provision ECS Cluster and deploy the application"

on:
  push:
    branches:
      - develop

jobs:
  provisioning:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: us-east-1

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply tfplan

      - name: Build docker image
        run: |
          export ECR_REPO_URL=$(terraform output ecr_repo | tr -d '"')
          docker build -t api_desafio_devops .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Tag docker image
        run: docker tag api_desafio_devops:latest $ECR_REPO_URL:latest

      - name: Push docker image to ECR
        run: docker push $ECR_REPO
